#manual: data/evals/dev/manual_upsampled.csv
anthropic: data/evals/dev/anthropic_balanced_apr_23.jsonl
# toolace: data/evals/dev/toolace_balanced_apr_22.jsonl
mt: data/evals/dev/mt_balanced_apr_30.jsonl
# mts: data/evals/dev/mts_balanced_apr_22.jsonl
#mask: data/evals/dev/mask_samples_balanced.jsonl
