#manual: data/evals/test/manual.csv
anthropic: data/evals/test/anthropic_test_balanced_apr_23.jsonl
# toolace: data/evals/test/toolace_test_balanced_apr_22.jsonl
mt: data/evals/test/mt_test_balanced_apr_30.jsonl
# mts: data/evals/test/mts_test_balanced_apr_22.jsonl
# mental_health: data/evals/test/mental_health_test_balanced_apr_22.jsonl
# redteaming: data/evals/test/redteaming_test_balanced_apr_22.jsonl
#mask: data/evals/test/mask_samples_balanced.jsonl
